spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/blackhorse?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: deary0628
  flyway:
    baseline-on-migrate: true
    locations: classpath:/db/migration
  redis:
    database: 0
    host: localhost
    port: 6379
    timeout: 10000
application:
  flight:
    url: http://localhost:8081
  flight-site:
    url: http://localhost:8082